### PR TITLE
Add Cloudflare API Token authentication support

### PR DESCRIPTION
**Pull request by bengalih**
This adds support for [Cloudflare Token authentication](https://support.cloudflare.com/hc/en-us/articles/115001376488-Configuring-Token-Authentication)

_(Hoping I did this right.  I have a PR for patch-6 which added the proxy support.
Since I wanted to get everything done now, I created this new bengalih-patch-1 branch and used the patch-6 as the base to do my edits.  When I submit the PR for this one it looks like it is combining all edits into one.  Assuming you approve patch-6 you can then approve this?  I'm not sure if I messed it up so you can't be atomic in your approval.  If I did this wrong, please give me some better guidance here.)_

### CODE REVIEW

**Comment by ulygit** [comment]
This would have been fine except that you've included the separate proxy-related changes as well. The problem with that is if we later need to revert changes, this will also remove proxy-related changes as well.

It's an unfortunate reality of this kind of collaboration that you often need to juggle concurrent modifications and keep them isolated from one another. Using separate branches is a common approach, but you can also use `git stash` to manage smaller changes in more lightweight fashion.

I do appreciate your effort on this. Thanks!

**Comment by bengalih** [comment]
Yes, as I mentioned previously I am using only the GH webpage to make these changes.
You previously mentioned you wanted them atomic, so I attempted to do that based on my understanding.
I created a separate branch for the proxy (patch-6) and submitted that.
However I didn't want to make all the changes for this prior to those changes being implemented, so I used patch-6 as a base for this next patch, assuming that it would be contingent upon patch-6 first being implemented.
As I stated in my initial comments I saw that it also included everything from patch-6, and I'm not sure why that is.  It doesn't make sense to me that if I am using patch-6 as a baseline that it then includes all those changes into this bengalih-patch-1.
I spent 20-30 minutes reading through the intro workflow on GH and it apparently failed to explain things enough to deal with these situations.
I don't really have the time to spend on the quirks of the platform, when I'm just trying to suggest changes.

I'm perfectly happy with you rejecting all these changes and simply using the exact code, or some change you deem to be appropriate to insert into the main code.

I don't really care about credit, etc.  I just would like the code to function and have the necessary options to work with standard CF records.

**Comment by ulygit** [comment]
I understand. I'm going to revisit the code tomorrow, so I'll integrate your changes then. I appreciate your taking your time with this.

**Comment by ulygit** [comment]
Fixed separately. Thanks for your suggestion! Note, I'll be adding a credit to you, but I haven't decided quite how to yet.

**Comment by bengalih** [comment]
No worries.  Tried latest version, all seems well.

**Comment by ulygit** [comment]
Thanks for confirming.

**Pull request closed without merging**
